"""task_user_id

Revision ID: 4b486e9de62d
Revises: 1375e7cdf402
Create Date: 2023-02-03 21:44:27.233965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b486e9de62d'
down_revision = '1375e7cdf402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_task_owner_id_user'), 'task', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_owner_id_user'), 'task', type_='foreignkey')
    op.drop_column('task', 'owner_id')
    # ### end Alembic commands ###
