"""task_application

Revision ID: 6be2343ef608
Revises: 4b486e9de62d
Create Date: 2023-02-09 22:22:16.594691

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6be2343ef608"
down_revision = "4b486e9de62d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_task_application_task_id_task")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_task_application_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_application")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_application")
    # ### end Alembic commands ###
