"""task_city_name

Revision ID: 7d4a5d2d00ef
Revises: 76c1e690382a
Create Date: 2023-03-04 19:28:12.541957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4a5d2d00ef'
down_revision = '76c1e690382a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('city_name', sa.String(length=256), nullable=True))
    op.create_foreign_key(op.f('fk_task_city_name_city'), 'task', 'city', ['city_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_city_name_city'), 'task', type_='foreignkey')
    op.drop_column('task', 'city_name')
    # ### end Alembic commands ###
