"""ondelete_cascade_task_application

Revision ID: d1921a934373
Revises: 6be2343ef608
Create Date: 2023-02-18 17:15:24.064245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1921a934373'
down_revision = '6be2343ef608'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_application_task_id_task', 'task_application', type_='foreignkey')
    op.drop_constraint('fk_task_application_user_id_user', 'task_application', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_application_user_id_user'), 'task_application', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_task_application_task_id_task'), 'task_application', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_application_task_id_task'), 'task_application', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_application_user_id_user'), 'task_application', type_='foreignkey')
    op.create_foreign_key('fk_task_application_user_id_user', 'task_application', 'user', ['user_id'], ['id'])
    op.create_foreign_key('fk_task_application_task_id_task', 'task_application', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
